### ISSUE TITLE
Use TOML as config format

### ISSUE THREAD

**Issue by danilshvalov** [danilshvalov/comrade#2]
Instead of the current config file, we could use TOML as the config format. For example, instead of the following config

```
# prefs.config
helper_window_move 100 100
touchpad_sensitivity 1.0
page_separator_color 0.9 0.9 0.9

# keys.config
open_document o
open_document_embedded <C-o>
open_document_embedded_from_current_path <C-S-o>
```

we could have

```toml
[options]
helper-window-move = [100, 100]
touchpad-sensitivity = 1.0
page-separator-color = [0.9, 0.9, 0.9]

[keymap]
o = "open_document"
C-o = "open_document_embedded"
C-S-o = "open_document_embedded_from_current_path"
some-key = "unbound"
```
